apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - image: rabbitmq
        name: rabbit
        ports:
        - containerPort: 5672
        resources: {}
status: {}

