apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-projeto
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: "/home/linconln"