apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbit
  name: rabbit-svc
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: p5672
  - port: 15672
    targetPort: 15672
    name: p15672
  selector:
    app: rabbit
status:
  loadBalancer: {}
